const express = require('express');
const router=express.Router();
const invoice = require('../../models/clientInvoice');
const jwt = require('jsonwebtoken');

//route to view invoice of users generated by admin
router.get('/myInvoice', isValidUser, (req, res) => {
	jwt.verify(req.token, 'secretKey', (err, authData) => {
			if (authData) {
				req.params = authData;
				// console.log(req.params)
				invoice.find({fullName: req.params.user.fullName }, (err, result) => {
					if (err) {
						return res.status(400).json()
					} else {
						return res.status(200).json({
							message: 'Invoice Fetched',
							result
						})				
					}
				})
			} else {
				res.status(403).json({message: 'Unauthorized'})
			}
		})
	});

function isValidUser(req, res, next) {
	const bearerHeader = req.headers['authorization'];
	if (typeof bearerHeader !== 'undefined') {
		req.token = bearerHeader;
		next();
	} else {
		res.status(403).json({
			message: 'Unauthorized request'
		})
	}
}

module.exports=router;